#ifndef TARRAYOPS_H
#define TARRAYOPS_H

///////////////////////////////////////////////////////////////////////////////
//
// WARNING: THIS FILE WAS GENERATED AUTOMATICALLY!
// YOU SHOULD MODIFY THE INPUT FILES INSTEAD OF CHANGING THIS FILE DIRECTLY!
//
// THE FOLLOWING INPUT FILES WERE USED TO MAKE THIS FILE:
//
// MakeOperators
// TArrayDefs.in
//
///////////////////////////////////////////////////////////////////////////////


inline MakeReturn<UnaryNode<FnArcCos,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
acos(const TArray & l)
{
  typedef UnaryNode<FnArcCos,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l)));
}

inline MakeReturn<UnaryNode<FnArcSin,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
asin(const TArray & l)
{
  typedef UnaryNode<FnArcSin,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l)));
}

inline MakeReturn<UnaryNode<FnArcTan,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
atan(const TArray & l)
{
  typedef UnaryNode<FnArcTan,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l)));
}

inline MakeReturn<UnaryNode<FnCeil,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
ceil(const TArray & l)
{
  typedef UnaryNode<FnCeil,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l)));
}

inline MakeReturn<UnaryNode<FnCos,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
cos(const TArray & l)
{
  typedef UnaryNode<FnCos,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l)));
}

inline MakeReturn<UnaryNode<FnHypCos,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
cosh(const TArray & l)
{
  typedef UnaryNode<FnHypCos,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l)));
}

inline MakeReturn<UnaryNode<FnExp,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
exp(const TArray & l)
{
  typedef UnaryNode<FnExp,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l)));
}

inline MakeReturn<UnaryNode<FnFabs,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
fabs(const TArray & l)
{
  typedef UnaryNode<FnFabs,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l)));
}

inline MakeReturn<UnaryNode<FnFloor,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
floor(const TArray & l)
{
  typedef UnaryNode<FnFloor,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l)));
}

inline MakeReturn<UnaryNode<FnLog,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
log(const TArray & l)
{
  typedef UnaryNode<FnLog,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l)));
}

inline MakeReturn<UnaryNode<FnLog10,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
log10(const TArray & l)
{
  typedef UnaryNode<FnLog10,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l)));
}

inline MakeReturn<UnaryNode<FnSin,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
sin(const TArray & l)
{
  typedef UnaryNode<FnSin,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l)));
}

inline MakeReturn<UnaryNode<FnHypSin,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
sinh(const TArray & l)
{
  typedef UnaryNode<FnHypSin,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l)));
}

inline MakeReturn<UnaryNode<FnSqrt,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
sqrt(const TArray & l)
{
  typedef UnaryNode<FnSqrt,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l)));
}

inline MakeReturn<UnaryNode<FnTan,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
tan(const TArray & l)
{
  typedef UnaryNode<FnTan,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l)));
}

inline MakeReturn<UnaryNode<FnHypTan,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
tanh(const TArray & l)
{
  typedef UnaryNode<FnHypTan,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l)));
}

inline MakeReturn<UnaryNode<OpUnaryMinus,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator-(const TArray & l)
{
  typedef UnaryNode<OpUnaryMinus,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l)));
}

inline MakeReturn<UnaryNode<OpUnaryPlus,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator+(const TArray & l)
{
  typedef UnaryNode<OpUnaryPlus,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l)));
}

inline MakeReturn<UnaryNode<OpBitwiseNot,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator~(const TArray & l)
{
  typedef UnaryNode<OpBitwiseNot,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l)));
}

inline MakeReturn<UnaryNode<OpIdentity,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
PETE_identity(const TArray & l)
{
  typedef UnaryNode<OpIdentity,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l)));
}

inline MakeReturn<UnaryNode<OpNot,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator!(const TArray & l)
{
  typedef UnaryNode<OpNot,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l)));
}

template<class T1>
inline typename MakeReturn<UnaryNode<OpCast<T1>,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
peteCast(const T1&, const TArray & l)
{
  typedef UnaryNode<OpCast<T1>,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l)));
}

inline MakeReturn<BinaryNode<OpAdd,
  CreateLeaf<TArray >::Leaf_t,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator+(const TArray & l,const TArray & r)
{
  typedef BinaryNode<OpAdd,
    CreateLeaf<TArray >::Leaf_t,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<TArray >::make(r)));
}

inline MakeReturn<BinaryNode<OpSubtract,
  CreateLeaf<TArray >::Leaf_t,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator-(const TArray & l,const TArray & r)
{
  typedef BinaryNode<OpSubtract,
    CreateLeaf<TArray >::Leaf_t,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<TArray >::make(r)));
}

inline MakeReturn<BinaryNode<OpMultiply,
  CreateLeaf<TArray >::Leaf_t,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator*(const TArray & l,const TArray & r)
{
  typedef BinaryNode<OpMultiply,
    CreateLeaf<TArray >::Leaf_t,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<TArray >::make(r)));
}

inline MakeReturn<BinaryNode<OpDivide,
  CreateLeaf<TArray >::Leaf_t,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator/(const TArray & l,const TArray & r)
{
  typedef BinaryNode<OpDivide,
    CreateLeaf<TArray >::Leaf_t,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<TArray >::make(r)));
}

inline MakeReturn<BinaryNode<OpMod,
  CreateLeaf<TArray >::Leaf_t,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator%(const TArray & l,const TArray & r)
{
  typedef BinaryNode<OpMod,
    CreateLeaf<TArray >::Leaf_t,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<TArray >::make(r)));
}

inline MakeReturn<BinaryNode<OpBitwiseAnd,
  CreateLeaf<TArray >::Leaf_t,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator&(const TArray & l,const TArray & r)
{
  typedef BinaryNode<OpBitwiseAnd,
    CreateLeaf<TArray >::Leaf_t,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<TArray >::make(r)));
}

inline MakeReturn<BinaryNode<OpBitwiseOr,
  CreateLeaf<TArray >::Leaf_t,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator|(const TArray & l,const TArray & r)
{
  typedef BinaryNode<OpBitwiseOr,
    CreateLeaf<TArray >::Leaf_t,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<TArray >::make(r)));
}

inline MakeReturn<BinaryNode<OpBitwiseXor,
  CreateLeaf<TArray >::Leaf_t,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator^(const TArray & l,const TArray & r)
{
  typedef BinaryNode<OpBitwiseXor,
    CreateLeaf<TArray >::Leaf_t,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<TArray >::make(r)));
}

inline MakeReturn<BinaryNode<FnLdexp,
  CreateLeaf<TArray >::Leaf_t,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
ldexp(const TArray & l,const TArray & r)
{
  typedef BinaryNode<FnLdexp,
    CreateLeaf<TArray >::Leaf_t,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<TArray >::make(r)));
}

inline MakeReturn<BinaryNode<FnPow,
  CreateLeaf<TArray >::Leaf_t,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
pow(const TArray & l,const TArray & r)
{
  typedef BinaryNode<FnPow,
    CreateLeaf<TArray >::Leaf_t,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<TArray >::make(r)));
}

inline MakeReturn<BinaryNode<FnFmod,
  CreateLeaf<TArray >::Leaf_t,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
fmod(const TArray & l,const TArray & r)
{
  typedef BinaryNode<FnFmod,
    CreateLeaf<TArray >::Leaf_t,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<TArray >::make(r)));
}

inline MakeReturn<BinaryNode<FnArcTan2,
  CreateLeaf<TArray >::Leaf_t,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
atan2(const TArray & l,const TArray & r)
{
  typedef BinaryNode<FnArcTan2,
    CreateLeaf<TArray >::Leaf_t,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<TArray >::make(r)));
}

inline MakeReturn<BinaryNode<OpLT,
  CreateLeaf<TArray >::Leaf_t,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator<(const TArray & l,const TArray & r)
{
  typedef BinaryNode<OpLT,
    CreateLeaf<TArray >::Leaf_t,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<TArray >::make(r)));
}

inline MakeReturn<BinaryNode<OpLE,
  CreateLeaf<TArray >::Leaf_t,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator<=(const TArray & l,const TArray & r)
{
  typedef BinaryNode<OpLE,
    CreateLeaf<TArray >::Leaf_t,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<TArray >::make(r)));
}

inline MakeReturn<BinaryNode<OpGT,
  CreateLeaf<TArray >::Leaf_t,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator>(const TArray & l,const TArray & r)
{
  typedef BinaryNode<OpGT,
    CreateLeaf<TArray >::Leaf_t,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<TArray >::make(r)));
}

inline MakeReturn<BinaryNode<OpGE,
  CreateLeaf<TArray >::Leaf_t,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator>=(const TArray & l,const TArray & r)
{
  typedef BinaryNode<OpGE,
    CreateLeaf<TArray >::Leaf_t,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<TArray >::make(r)));
}

inline MakeReturn<BinaryNode<OpEQ,
  CreateLeaf<TArray >::Leaf_t,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator==(const TArray & l,const TArray & r)
{
  typedef BinaryNode<OpEQ,
    CreateLeaf<TArray >::Leaf_t,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<TArray >::make(r)));
}

inline MakeReturn<BinaryNode<OpNE,
  CreateLeaf<TArray >::Leaf_t,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator!=(const TArray & l,const TArray & r)
{
  typedef BinaryNode<OpNE,
    CreateLeaf<TArray >::Leaf_t,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<TArray >::make(r)));
}

inline MakeReturn<BinaryNode<OpAnd,
  CreateLeaf<TArray >::Leaf_t,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator&&(const TArray & l,const TArray & r)
{
  typedef BinaryNode<OpAnd,
    CreateLeaf<TArray >::Leaf_t,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<TArray >::make(r)));
}

inline MakeReturn<BinaryNode<OpOr,
  CreateLeaf<TArray >::Leaf_t,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator||(const TArray & l,const TArray & r)
{
  typedef BinaryNode<OpOr,
    CreateLeaf<TArray >::Leaf_t,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<TArray >::make(r)));
}

inline MakeReturn<BinaryNode<OpLeftShift,
  CreateLeaf<TArray >::Leaf_t,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator<<(const TArray & l,const TArray & r)
{
  typedef BinaryNode<OpLeftShift,
    CreateLeaf<TArray >::Leaf_t,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<TArray >::make(r)));
}

inline MakeReturn<BinaryNode<OpRightShift,
  CreateLeaf<TArray >::Leaf_t,
  CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator>>(const TArray & l,const TArray & r)
{
  typedef BinaryNode<OpRightShift,
    CreateLeaf<TArray >::Leaf_t,
    CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpAdd,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator+(const TArray & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpAdd,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpSubtract,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator-(const TArray & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpSubtract,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpMultiply,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator*(const TArray & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpMultiply,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpDivide,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator/(const TArray & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpDivide,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpMod,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator%(const TArray & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpMod,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpBitwiseAnd,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator&(const TArray & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpBitwiseAnd,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpBitwiseOr,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator|(const TArray & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpBitwiseOr,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpBitwiseXor,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator^(const TArray & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpBitwiseXor,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<FnLdexp,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
ldexp(const TArray & l,const Expression<T2> & r)
{
  typedef BinaryNode<FnLdexp,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<FnPow,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
pow(const TArray & l,const Expression<T2> & r)
{
  typedef BinaryNode<FnPow,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<FnFmod,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
fmod(const TArray & l,const Expression<T2> & r)
{
  typedef BinaryNode<FnFmod,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<FnArcTan2,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
atan2(const TArray & l,const Expression<T2> & r)
{
  typedef BinaryNode<FnArcTan2,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpLT,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator<(const TArray & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpLT,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpLE,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator<=(const TArray & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpLE,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpGT,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator>(const TArray & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpGT,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpGE,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator>=(const TArray & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpGE,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpEQ,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator==(const TArray & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpEQ,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpNE,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator!=(const TArray & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpNE,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpAnd,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator&&(const TArray & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpAnd,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpOr,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator||(const TArray & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpOr,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpLeftShift,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator<<(const TArray & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpLeftShift,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpRightShift,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator>>(const TArray & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpRightShift,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpAdd,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator+(const Expression<T1> & l,const TArray & r)
{
  typedef BinaryNode<OpAdd,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpSubtract,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator-(const Expression<T1> & l,const TArray & r)
{
  typedef BinaryNode<OpSubtract,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpMultiply,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator*(const Expression<T1> & l,const TArray & r)
{
  typedef BinaryNode<OpMultiply,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpDivide,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator/(const Expression<T1> & l,const TArray & r)
{
  typedef BinaryNode<OpDivide,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpMod,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator%(const Expression<T1> & l,const TArray & r)
{
  typedef BinaryNode<OpMod,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpBitwiseAnd,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator&(const Expression<T1> & l,const TArray & r)
{
  typedef BinaryNode<OpBitwiseAnd,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpBitwiseOr,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator|(const Expression<T1> & l,const TArray & r)
{
  typedef BinaryNode<OpBitwiseOr,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpBitwiseXor,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator^(const Expression<T1> & l,const TArray & r)
{
  typedef BinaryNode<OpBitwiseXor,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<FnLdexp,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
ldexp(const Expression<T1> & l,const TArray & r)
{
  typedef BinaryNode<FnLdexp,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<FnPow,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
pow(const Expression<T1> & l,const TArray & r)
{
  typedef BinaryNode<FnPow,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<FnFmod,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
fmod(const Expression<T1> & l,const TArray & r)
{
  typedef BinaryNode<FnFmod,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<FnArcTan2,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
atan2(const Expression<T1> & l,const TArray & r)
{
  typedef BinaryNode<FnArcTan2,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpLT,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator<(const Expression<T1> & l,const TArray & r)
{
  typedef BinaryNode<OpLT,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpLE,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator<=(const Expression<T1> & l,const TArray & r)
{
  typedef BinaryNode<OpLE,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpGT,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator>(const Expression<T1> & l,const TArray & r)
{
  typedef BinaryNode<OpGT,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpGE,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator>=(const Expression<T1> & l,const TArray & r)
{
  typedef BinaryNode<OpGE,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpEQ,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator==(const Expression<T1> & l,const TArray & r)
{
  typedef BinaryNode<OpEQ,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpNE,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator!=(const Expression<T1> & l,const TArray & r)
{
  typedef BinaryNode<OpNE,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpAnd,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator&&(const Expression<T1> & l,const TArray & r)
{
  typedef BinaryNode<OpAnd,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpOr,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator||(const Expression<T1> & l,const TArray & r)
{
  typedef BinaryNode<OpOr,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpLeftShift,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator<<(const Expression<T1> & l,const TArray & r)
{
  typedef BinaryNode<OpLeftShift,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpRightShift,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator>>(const Expression<T1> & l,const TArray & r)
{
  typedef BinaryNode<OpRightShift,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpAdd,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator+(const TArray & l,const T2 & r)
{
  typedef BinaryNode<OpAdd,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpSubtract,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator-(const TArray & l,const T2 & r)
{
  typedef BinaryNode<OpSubtract,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpMultiply,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator*(const TArray & l,const T2 & r)
{
  typedef BinaryNode<OpMultiply,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpDivide,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator/(const TArray & l,const T2 & r)
{
  typedef BinaryNode<OpDivide,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpMod,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator%(const TArray & l,const T2 & r)
{
  typedef BinaryNode<OpMod,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpBitwiseAnd,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator&(const TArray & l,const T2 & r)
{
  typedef BinaryNode<OpBitwiseAnd,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpBitwiseOr,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator|(const TArray & l,const T2 & r)
{
  typedef BinaryNode<OpBitwiseOr,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpBitwiseXor,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator^(const TArray & l,const T2 & r)
{
  typedef BinaryNode<OpBitwiseXor,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<FnLdexp,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
ldexp(const TArray & l,const T2 & r)
{
  typedef BinaryNode<FnLdexp,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<FnPow,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
pow(const TArray & l,const T2 & r)
{
  typedef BinaryNode<FnPow,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<FnFmod,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
fmod(const TArray & l,const T2 & r)
{
  typedef BinaryNode<FnFmod,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<FnArcTan2,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
atan2(const TArray & l,const T2 & r)
{
  typedef BinaryNode<FnArcTan2,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpLT,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator<(const TArray & l,const T2 & r)
{
  typedef BinaryNode<OpLT,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpLE,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator<=(const TArray & l,const T2 & r)
{
  typedef BinaryNode<OpLE,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpGT,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator>(const TArray & l,const T2 & r)
{
  typedef BinaryNode<OpGT,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpGE,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator>=(const TArray & l,const T2 & r)
{
  typedef BinaryNode<OpGE,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpEQ,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator==(const TArray & l,const T2 & r)
{
  typedef BinaryNode<OpEQ,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpNE,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator!=(const TArray & l,const T2 & r)
{
  typedef BinaryNode<OpNE,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpAnd,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator&&(const TArray & l,const T2 & r)
{
  typedef BinaryNode<OpAnd,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpOr,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator||(const TArray & l,const T2 & r)
{
  typedef BinaryNode<OpOr,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpLeftShift,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator<<(const TArray & l,const T2 & r)
{
  typedef BinaryNode<OpLeftShift,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T2>
inline typename MakeReturn<BinaryNode<OpRightShift,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator>>(const TArray & l,const T2 & r)
{
  typedef BinaryNode<OpRightShift,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpAdd,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator+(const T1 & l,const TArray & r)
{
  typedef BinaryNode<OpAdd,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpSubtract,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator-(const T1 & l,const TArray & r)
{
  typedef BinaryNode<OpSubtract,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpMultiply,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator*(const T1 & l,const TArray & r)
{
  typedef BinaryNode<OpMultiply,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpDivide,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator/(const T1 & l,const TArray & r)
{
  typedef BinaryNode<OpDivide,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpMod,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator%(const T1 & l,const TArray & r)
{
  typedef BinaryNode<OpMod,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpBitwiseAnd,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator&(const T1 & l,const TArray & r)
{
  typedef BinaryNode<OpBitwiseAnd,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpBitwiseOr,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator|(const T1 & l,const TArray & r)
{
  typedef BinaryNode<OpBitwiseOr,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpBitwiseXor,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator^(const T1 & l,const TArray & r)
{
  typedef BinaryNode<OpBitwiseXor,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<FnLdexp,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
ldexp(const T1 & l,const TArray & r)
{
  typedef BinaryNode<FnLdexp,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<FnPow,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
pow(const T1 & l,const TArray & r)
{
  typedef BinaryNode<FnPow,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<FnFmod,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
fmod(const T1 & l,const TArray & r)
{
  typedef BinaryNode<FnFmod,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<FnArcTan2,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
atan2(const T1 & l,const TArray & r)
{
  typedef BinaryNode<FnArcTan2,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpLT,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator<(const T1 & l,const TArray & r)
{
  typedef BinaryNode<OpLT,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpLE,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator<=(const T1 & l,const TArray & r)
{
  typedef BinaryNode<OpLE,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpGT,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator>(const T1 & l,const TArray & r)
{
  typedef BinaryNode<OpGT,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpGE,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator>=(const T1 & l,const TArray & r)
{
  typedef BinaryNode<OpGE,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpEQ,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator==(const T1 & l,const TArray & r)
{
  typedef BinaryNode<OpEQ,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpNE,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator!=(const T1 & l,const TArray & r)
{
  typedef BinaryNode<OpNE,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpAnd,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator&&(const T1 & l,const TArray & r)
{
  typedef BinaryNode<OpAnd,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpOr,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator||(const T1 & l,const TArray & r)
{
  typedef BinaryNode<OpOr,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<TArray >::make(r)));
}
#ifdef PETE_ALLOW_SCALAR_SHIFT

template<class T1>
inline typename MakeReturn<BinaryNode<OpLeftShift,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator<<(const T1 & l,const TArray & r)
{
  typedef BinaryNode<OpLeftShift,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<TArray >::make(r)));
}

template<class T1>
inline typename MakeReturn<BinaryNode<OpRightShift,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<TArray >::Leaf_t> >::Expression_t
operator>>(const T1 & l,const TArray & r)
{
  typedef BinaryNode<OpRightShift,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<TArray >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<TArray >::make(r)));
}
#endif // PETE_ALLOW_SCALAR_SHIFT

template<class T2,class T3>
inline typename MakeReturn<TrinaryNode<FnWhere,
  typename CreateLeaf<TArray >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t,
  typename CreateLeaf<T3 >::Leaf_t> >::Expression_t
where(const TArray & c,const T2 & t,const T3 & f)
{
  typedef TrinaryNode<FnWhere,
    typename CreateLeaf<TArray >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t,
    typename CreateLeaf<T3 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<TArray >::make(c),
    CreateLeaf<T2 >::make(t),
    CreateLeaf<T3 >::make(f)));
}
#ifndef PETE_EXPRESSION_OPERATORS
#define PETE_EXPRESSION_OPERATORS

template<class T1>
inline typename MakeReturn<UnaryNode<FnArcCos,
  typename CreateLeaf<Expression<T1> >::Leaf_t> >::Expression_t
acos(const Expression<T1> & l)
{
  typedef UnaryNode<FnArcCos,
    typename CreateLeaf<Expression<T1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l)));
}

template<class T1>
inline typename MakeReturn<UnaryNode<FnArcSin,
  typename CreateLeaf<Expression<T1> >::Leaf_t> >::Expression_t
asin(const Expression<T1> & l)
{
  typedef UnaryNode<FnArcSin,
    typename CreateLeaf<Expression<T1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l)));
}

template<class T1>
inline typename MakeReturn<UnaryNode<FnArcTan,
  typename CreateLeaf<Expression<T1> >::Leaf_t> >::Expression_t
atan(const Expression<T1> & l)
{
  typedef UnaryNode<FnArcTan,
    typename CreateLeaf<Expression<T1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l)));
}

template<class T1>
inline typename MakeReturn<UnaryNode<FnCeil,
  typename CreateLeaf<Expression<T1> >::Leaf_t> >::Expression_t
ceil(const Expression<T1> & l)
{
  typedef UnaryNode<FnCeil,
    typename CreateLeaf<Expression<T1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l)));
}

template<class T1>
inline typename MakeReturn<UnaryNode<FnCos,
  typename CreateLeaf<Expression<T1> >::Leaf_t> >::Expression_t
cos(const Expression<T1> & l)
{
  typedef UnaryNode<FnCos,
    typename CreateLeaf<Expression<T1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l)));
}

template<class T1>
inline typename MakeReturn<UnaryNode<FnHypCos,
  typename CreateLeaf<Expression<T1> >::Leaf_t> >::Expression_t
cosh(const Expression<T1> & l)
{
  typedef UnaryNode<FnHypCos,
    typename CreateLeaf<Expression<T1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l)));
}

template<class T1>
inline typename MakeReturn<UnaryNode<FnExp,
  typename CreateLeaf<Expression<T1> >::Leaf_t> >::Expression_t
exp(const Expression<T1> & l)
{
  typedef UnaryNode<FnExp,
    typename CreateLeaf<Expression<T1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l)));
}

template<class T1>
inline typename MakeReturn<UnaryNode<FnFabs,
  typename CreateLeaf<Expression<T1> >::Leaf_t> >::Expression_t
fabs(const Expression<T1> & l)
{
  typedef UnaryNode<FnFabs,
    typename CreateLeaf<Expression<T1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l)));
}

template<class T1>
inline typename MakeReturn<UnaryNode<FnFloor,
  typename CreateLeaf<Expression<T1> >::Leaf_t> >::Expression_t
floor(const Expression<T1> & l)
{
  typedef UnaryNode<FnFloor,
    typename CreateLeaf<Expression<T1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l)));
}

template<class T1>
inline typename MakeReturn<UnaryNode<FnLog,
  typename CreateLeaf<Expression<T1> >::Leaf_t> >::Expression_t
log(const Expression<T1> & l)
{
  typedef UnaryNode<FnLog,
    typename CreateLeaf<Expression<T1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l)));
}

template<class T1>
inline typename MakeReturn<UnaryNode<FnLog10,
  typename CreateLeaf<Expression<T1> >::Leaf_t> >::Expression_t
log10(const Expression<T1> & l)
{
  typedef UnaryNode<FnLog10,
    typename CreateLeaf<Expression<T1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l)));
}

template<class T1>
inline typename MakeReturn<UnaryNode<FnSin,
  typename CreateLeaf<Expression<T1> >::Leaf_t> >::Expression_t
sin(const Expression<T1> & l)
{
  typedef UnaryNode<FnSin,
    typename CreateLeaf<Expression<T1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l)));
}

template<class T1>
inline typename MakeReturn<UnaryNode<FnHypSin,
  typename CreateLeaf<Expression<T1> >::Leaf_t> >::Expression_t
sinh(const Expression<T1> & l)
{
  typedef UnaryNode<FnHypSin,
    typename CreateLeaf<Expression<T1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l)));
}

template<class T1>
inline typename MakeReturn<UnaryNode<FnSqrt,
  typename CreateLeaf<Expression<T1> >::Leaf_t> >::Expression_t
sqrt(const Expression<T1> & l)
{
  typedef UnaryNode<FnSqrt,
    typename CreateLeaf<Expression<T1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l)));
}

template<class T1>
inline typename MakeReturn<UnaryNode<FnTan,
  typename CreateLeaf<Expression<T1> >::Leaf_t> >::Expression_t
tan(const Expression<T1> & l)
{
  typedef UnaryNode<FnTan,
    typename CreateLeaf<Expression<T1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l)));
}

template<class T1>
inline typename MakeReturn<UnaryNode<FnHypTan,
  typename CreateLeaf<Expression<T1> >::Leaf_t> >::Expression_t
tanh(const Expression<T1> & l)
{
  typedef UnaryNode<FnHypTan,
    typename CreateLeaf<Expression<T1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l)));
}

template<class T1>
inline typename MakeReturn<UnaryNode<OpUnaryMinus,
  typename CreateLeaf<Expression<T1> >::Leaf_t> >::Expression_t
operator-(const Expression<T1> & l)
{
  typedef UnaryNode<OpUnaryMinus,
    typename CreateLeaf<Expression<T1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l)));
}

template<class T1>
inline typename MakeReturn<UnaryNode<OpUnaryPlus,
  typename CreateLeaf<Expression<T1> >::Leaf_t> >::Expression_t
operator+(const Expression<T1> & l)
{
  typedef UnaryNode<OpUnaryPlus,
    typename CreateLeaf<Expression<T1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l)));
}

template<class T1>
inline typename MakeReturn<UnaryNode<OpBitwiseNot,
  typename CreateLeaf<Expression<T1> >::Leaf_t> >::Expression_t
operator~(const Expression<T1> & l)
{
  typedef UnaryNode<OpBitwiseNot,
    typename CreateLeaf<Expression<T1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l)));
}

template<class T1>
inline typename MakeReturn<UnaryNode<OpIdentity,
  typename CreateLeaf<Expression<T1> >::Leaf_t> >::Expression_t
PETE_identity(const Expression<T1> & l)
{
  typedef UnaryNode<OpIdentity,
    typename CreateLeaf<Expression<T1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l)));
}

template<class T1>
inline typename MakeReturn<UnaryNode<OpNot,
  typename CreateLeaf<Expression<T1> >::Leaf_t> >::Expression_t
operator!(const Expression<T1> & l)
{
  typedef UnaryNode<OpNot,
    typename CreateLeaf<Expression<T1> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l)));
}

template<class T1,class T2>
inline typename MakeReturn<UnaryNode<OpCast<T1>,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
peteCast(const T1&, const Expression<T2> & l)
{
  typedef UnaryNode<OpCast<T1>,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T2> >::make(l)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpAdd,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator+(const Expression<T1> & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpAdd,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpSubtract,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator-(const Expression<T1> & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpSubtract,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpMultiply,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator*(const Expression<T1> & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpMultiply,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpDivide,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator/(const Expression<T1> & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpDivide,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpMod,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator%(const Expression<T1> & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpMod,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpBitwiseAnd,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator&(const Expression<T1> & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpBitwiseAnd,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpBitwiseOr,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator|(const Expression<T1> & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpBitwiseOr,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpBitwiseXor,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator^(const Expression<T1> & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpBitwiseXor,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<FnLdexp,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
ldexp(const Expression<T1> & l,const Expression<T2> & r)
{
  typedef BinaryNode<FnLdexp,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<FnPow,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
pow(const Expression<T1> & l,const Expression<T2> & r)
{
  typedef BinaryNode<FnPow,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<FnFmod,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
fmod(const Expression<T1> & l,const Expression<T2> & r)
{
  typedef BinaryNode<FnFmod,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<FnArcTan2,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
atan2(const Expression<T1> & l,const Expression<T2> & r)
{
  typedef BinaryNode<FnArcTan2,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpLT,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator<(const Expression<T1> & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpLT,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpLE,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator<=(const Expression<T1> & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpLE,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpGT,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator>(const Expression<T1> & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpGT,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpGE,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator>=(const Expression<T1> & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpGE,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpEQ,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator==(const Expression<T1> & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpEQ,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpNE,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator!=(const Expression<T1> & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpNE,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpAnd,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator&&(const Expression<T1> & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpAnd,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpOr,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator||(const Expression<T1> & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpOr,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpLeftShift,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator<<(const Expression<T1> & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpLeftShift,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpRightShift,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator>>(const Expression<T1> & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpRightShift,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpAdd,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator+(const Expression<T1> & l,const T2 & r)
{
  typedef BinaryNode<OpAdd,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpSubtract,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator-(const Expression<T1> & l,const T2 & r)
{
  typedef BinaryNode<OpSubtract,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpMultiply,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator*(const Expression<T1> & l,const T2 & r)
{
  typedef BinaryNode<OpMultiply,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpDivide,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator/(const Expression<T1> & l,const T2 & r)
{
  typedef BinaryNode<OpDivide,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpMod,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator%(const Expression<T1> & l,const T2 & r)
{
  typedef BinaryNode<OpMod,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpBitwiseAnd,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator&(const Expression<T1> & l,const T2 & r)
{
  typedef BinaryNode<OpBitwiseAnd,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpBitwiseOr,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator|(const Expression<T1> & l,const T2 & r)
{
  typedef BinaryNode<OpBitwiseOr,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpBitwiseXor,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator^(const Expression<T1> & l,const T2 & r)
{
  typedef BinaryNode<OpBitwiseXor,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<FnLdexp,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
ldexp(const Expression<T1> & l,const T2 & r)
{
  typedef BinaryNode<FnLdexp,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<FnPow,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
pow(const Expression<T1> & l,const T2 & r)
{
  typedef BinaryNode<FnPow,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<FnFmod,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
fmod(const Expression<T1> & l,const T2 & r)
{
  typedef BinaryNode<FnFmod,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<FnArcTan2,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
atan2(const Expression<T1> & l,const T2 & r)
{
  typedef BinaryNode<FnArcTan2,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpLT,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator<(const Expression<T1> & l,const T2 & r)
{
  typedef BinaryNode<OpLT,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpLE,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator<=(const Expression<T1> & l,const T2 & r)
{
  typedef BinaryNode<OpLE,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpGT,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator>(const Expression<T1> & l,const T2 & r)
{
  typedef BinaryNode<OpGT,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpGE,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator>=(const Expression<T1> & l,const T2 & r)
{
  typedef BinaryNode<OpGE,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpEQ,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator==(const Expression<T1> & l,const T2 & r)
{
  typedef BinaryNode<OpEQ,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpNE,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator!=(const Expression<T1> & l,const T2 & r)
{
  typedef BinaryNode<OpNE,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpAnd,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator&&(const Expression<T1> & l,const T2 & r)
{
  typedef BinaryNode<OpAnd,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpOr,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator||(const Expression<T1> & l,const T2 & r)
{
  typedef BinaryNode<OpOr,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpLeftShift,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator<<(const Expression<T1> & l,const T2 & r)
{
  typedef BinaryNode<OpLeftShift,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpRightShift,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t> >::Expression_t
operator>>(const Expression<T1> & l,const T2 & r)
{
  typedef BinaryNode<OpRightShift,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(l),
    CreateLeaf<T2 >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpAdd,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator+(const T1 & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpAdd,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpSubtract,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator-(const T1 & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpSubtract,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpMultiply,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator*(const T1 & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpMultiply,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpDivide,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator/(const T1 & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpDivide,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpMod,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator%(const T1 & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpMod,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpBitwiseAnd,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator&(const T1 & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpBitwiseAnd,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpBitwiseOr,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator|(const T1 & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpBitwiseOr,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpBitwiseXor,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator^(const T1 & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpBitwiseXor,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<FnLdexp,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
ldexp(const T1 & l,const Expression<T2> & r)
{
  typedef BinaryNode<FnLdexp,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<FnPow,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
pow(const T1 & l,const Expression<T2> & r)
{
  typedef BinaryNode<FnPow,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<FnFmod,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
fmod(const T1 & l,const Expression<T2> & r)
{
  typedef BinaryNode<FnFmod,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<FnArcTan2,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
atan2(const T1 & l,const Expression<T2> & r)
{
  typedef BinaryNode<FnArcTan2,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpLT,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator<(const T1 & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpLT,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpLE,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator<=(const T1 & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpLE,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpGT,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator>(const T1 & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpGT,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpGE,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator>=(const T1 & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpGE,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpEQ,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator==(const T1 & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpEQ,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpNE,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator!=(const T1 & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpNE,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpAnd,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator&&(const T1 & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpAnd,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpOr,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator||(const T1 & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpOr,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}
#ifdef PETE_ALLOW_SCALAR_SHIFT

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpLeftShift,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator<<(const T1 & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpLeftShift,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}

template<class T1,class T2>
inline typename MakeReturn<BinaryNode<OpRightShift,
  typename CreateLeaf<T1 >::Leaf_t,
  typename CreateLeaf<Expression<T2> >::Leaf_t> >::Expression_t
operator>>(const T1 & l,const Expression<T2> & r)
{
  typedef BinaryNode<OpRightShift,
    typename CreateLeaf<T1 >::Leaf_t,
    typename CreateLeaf<Expression<T2> >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<T1 >::make(l),
    CreateLeaf<Expression<T2> >::make(r)));
}
#endif // PETE_ALLOW_SCALAR_SHIFT

template<class T1,class T2,class T3>
inline typename MakeReturn<TrinaryNode<FnWhere,
  typename CreateLeaf<Expression<T1> >::Leaf_t,
  typename CreateLeaf<T2 >::Leaf_t,
  typename CreateLeaf<T3 >::Leaf_t> >::Expression_t
where(const Expression<T1> & c,const T2 & t,const T3 & f)
{
  typedef TrinaryNode<FnWhere,
    typename CreateLeaf<Expression<T1> >::Leaf_t,
    typename CreateLeaf<T2 >::Leaf_t,
    typename CreateLeaf<T3 >::Leaf_t> Tree_t;
  return MakeReturn<Tree_t>::make(Tree_t(
    CreateLeaf<Expression<T1> >::make(c),
    CreateLeaf<T2 >::make(t),
    CreateLeaf<T3 >::make(f)));
}
#endif  // PETE_EXPRESSION_OPERATORS

#endif // TARRAYOPS_H

